services:
  postgresql:
    image: postgres:latest
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: economy
      POSTGRES_USER: chikina
      POSTGRES_PASSWORD: test12345
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
